server:
  port: 8012
  context-path: /snow
mybatis:
  type-aliases-package: com.snow.common.mode
#指定了mybatis基础配置文件和实体类映射文件的地址
  config-locations: classpath:mybatis-config.xml
  mapper-locations: classpath:com/snow/dam/core/mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/snow?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

project:
#参数传递
    name: snowName
#传递配置属性
    content: "我们项目名称为：${project.name}"

